name: Deploy Docker Container to GHCR

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for tags that start with 'v'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'  # Default value if not specified

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Get Latest Tag'
        id: get_latest_tag
        run: |
          # Fetch all tags
          git fetch --tags
          # Get the latest tag
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: 'Build and Push Docker Image'
        run: |
          # Use the version from the tag or the input if running manually
          VERSION=${GITHUB_REF#refs/tags/}
          if [ -z "$VERSION" ]; then
            VERSION=${{ github.event.inputs.version }}
          fi
          
          # Build the Docker image with the version tag
          docker build --build-arg VERSION=${VERSION} . --tag ghcr.io/zivoy/libpostal-rest:${VERSION}
          docker push ghcr.io/zivoy/libpostal-rest:${VERSION}
          
          # Tag the image as 'latest' only if it is the latest version
          if [ "${VERSION}" == "${LATEST_TAG}" ]; then
            docker tag ghcr.io/zivoy/libpostal-rest:${VERSION} ghcr.io/zivoy/libpostal-rest:latest
            docker push ghcr.io/zivoy/libpostal-rest:latest
          fi
